import sys
import time
import random
import pandas as pd

sys.path.insert(0, ".")

from src.agent import AppleSupportAgent


GOLDEN_PATH = "data/golden/intent_labeling.csv"
OUTPUT_PATH = "data/processed/agent_evaluation.csv"

# Retry configuration for Groq transient/API errors
MAX_RETRIES = 5
RETRY_DELAYS = [5, 10, 20, 30, 45]

# Delay between successful/failed requests to stay under TPM limits
REQUEST_DELAY = 12


def run_with_retry(agent, customer_text):
    """
    Run the agent with retries for Groq 400/429 errors.
    Returns:
        result, status, error_message
    """

    last_error = ""

    for attempt in range(MAX_RETRIES):

        try:
            result = agent.run(customer_text)

            return result, "success", ""

        except Exception as e:

            last_error = str(e)

            # Retry Groq JSON validation and rate-limit errors
            if "400" in last_error or "429" in last_error:

                if attempt < MAX_RETRIES - 1:

                    delay = RETRY_DELAYS[attempt] + random.uniform(0, 2)

                    print(
                        f"  Retry {attempt + 1}/{MAX_RETRIES - 1} "
                        f"after {delay:.1f}s..."
                    )

                    time.sleep(delay)

                    continue

            # Non-retryable error or all retries exhausted
            return None, "error", last_error

    return None, "error", last_error


def main():

    print("Loading golden evaluation set...")

    golden = pd.read_csv(
        GOLDEN_PATH,
        dtype=str
    )

    # Only manually labelled examples
    golden = golden[
        golden["intent_label"].notna()
    ].copy()

    golden = golden.reset_index(drop=True)

    print(f"Golden examples: {len(golden)}")

    # ---------------------------------------------------------
    # Load previous evaluation
    # ---------------------------------------------------------

    try:

        existing = pd.read_csv(
            OUTPUT_PATH,
            dtype=str
        )

        print(
            f"Existing evaluation rows: {len(existing)}"
        )

    except FileNotFoundError:

        existing = pd.DataFrame()

        print("No previous evaluation found.")

    # ---------------------------------------------------------
    # Determine which examples are already successfully done
    # ---------------------------------------------------------

    successful_ids = set()

    if not existing.empty:

        if "generation_status" in existing.columns:

            # IMPORTANT:
            # Old-format rows have NaN in generation_status.
            # Those rows were already successfully generated by
            # the previous evaluator, so treat NaN as success.
            status = existing["generation_status"].fillna("success")

            successful_ids = set(
                existing.loc[
                    status == "success",
                    "customer_tweet_id"
                ].astype(str)
            )

        else:

            # Completely old-format evaluation file.
            # Every existing row is considered successful.
            successful_ids = set(
                existing[
                    "customer_tweet_id"
                ].astype(str)
            )

    print(
        f"Already completed successfully: "
        f"{len(successful_ids)}"
    )

    print(
        f"Remaining: "
        f"{len(golden) - len(successful_ids)}"
    )

    # ---------------------------------------------------------
    # Initialize agent
    # ---------------------------------------------------------

    print("\nLoading AppleSupport agent...")

    agent = AppleSupportAgent()

    new_results = []

    # ---------------------------------------------------------
    # Process golden examples
    # ---------------------------------------------------------

    for position, row in golden.iterrows():

        tweet_id = str(
            row["customer_tweet_id"]
        )

        # Skip examples that were successfully evaluated
        if tweet_id in successful_ids:
            continue

        customer_text = str(
            row["customer_text"]
        )

        gold_intent = str(
            row["intent_label"]
        )

        # -----------------------------------------------------
        # Rate-limit protection
        # -----------------------------------------------------

        time.sleep(REQUEST_DELAY)

        # -----------------------------------------------------
        # Run agent with retry
        # -----------------------------------------------------

        result, status, error_message = run_with_retry(
            agent,
            customer_text
        )

        # -----------------------------------------------------
        # Successful generation
        # -----------------------------------------------------

        if status == "success":

            record = {
                "customer_tweet_id": tweet_id,
                "customer_text": customer_text,
                "gold_intent": gold_intent,

                "predicted_intent": result.get(
                    "intent",
                    ""
                ),

                "intent_confidence": result.get(
                    "intent_confidence",
                    ""
                ),

                "intent_margin": result.get(
                    "intent_margin",
                    ""
                ),

                "retrieval_top1_similarity": result.get(
                    "retrieval_top1_similarity",
                    ""
                ),

                "reply": result.get(
                    "reply",
                    ""
                ),

                "should_escalate": result.get(
                    "should_escalate",
                    ""
                ),

                "escalation_reason": result.get(
                    "escalation_reason",
                    ""
                ),

                "llm_escalation_suggestion": result.get(
                    "llm_escalation_suggestion",
                    ""
                ),

                "evidence_used": result.get(
                    "evidence_used",
                    ""
                ),

                "generation_status": "success",

                "generation_error": ""
            }

            print(
                f"Processed {position + 1}/{len(golden)}"
            )

        # -----------------------------------------------------
        # Failed generation
        # -----------------------------------------------------

        else:

            record = {
                "customer_tweet_id": tweet_id,
                "customer_text": customer_text,
                "gold_intent": gold_intent,

                "predicted_intent": "",
                "intent_confidence": "",
                "intent_margin": "",
                "retrieval_top1_similarity": "",

                "reply": "",

                "should_escalate": "",
                "escalation_reason": "",
                "llm_escalation_suggestion": "",
                "evidence_used": "",

                "generation_status": "error",

                "generation_error": error_message
            }

            print(
                f"ERROR on example {tweet_id}: "
                f"{error_message}"
            )

        new_results.append(record)

        # -----------------------------------------------------
        # Save after EVERY example
        # -----------------------------------------------------

        new_df = pd.DataFrame(new_results)

        if not existing.empty:

            combined = pd.concat(
                [
                    existing,
                    new_df
                ],
                ignore_index=True
            )

        else:

            combined = new_df

        combined.to_csv(
            OUTPUT_PATH,
            index=False
        )

    # ---------------------------------------------------------
    # Final summary
    # ---------------------------------------------------------

    print("\nEvaluation finished.")

    final = pd.read_csv(
        OUTPUT_PATH,
        dtype=str
    )

    print(
        f"Total saved rows: {len(final)}"
    )

    if "generation_status" in final.columns:

        print("\nGeneration status:")

        print(
            final[
                "generation_status"
            ].fillna("success").value_counts()
        )

        successful = final[
            final[
                "generation_status"
            ].fillna("success") == "success"
        ]

        print(
            f"\nSuccessful evaluations: "
            f"{len(successful)}/{len(golden)}"
        )


if __name__ == "__main__":
    main()